#+TITLE: MarkSheet
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="marksheet.css" />
#+HTML_HEAD_EXTRA: <meta name="viewport" content="width=device-width, initial-scale=1.0" />

By {{{author}}}

* Purpose

MarkSheet lets you generate Microsoft Excel (XLSX) files from an XML ot text description of the marking scheme (see [[file:sample.xml]] and [[file:sample.txt]]).
Whilst these files can be generated by hand, it was designed for use with exam-setting LaTeX classes that produce the appropriate text file alongside the generation of the PDF version of the exam papers and/or marking scheme.

* Download

** Binary

[[file:target/marksheet-2.0-SNAPSHOT.jar][Runnable JAR (dependencies included)]]

** Source

[[https://github.com/peadargrant/marksheet/][Sources on Github]]

* Marking scheme

Each question consists of a number of constituent parts. The program sets up the required formulae and allows taking the best of a number of equally-weighted questions.

** XML format

[[file:sample.xml][XML input]]

#+INCLUDE: "sample.xml" src xml

[[file:sample_from_xml.xlsx][XLSX output]]

** Text format

[[file:sample.txt][TXT input]]

#+INCLUDE: "sample.txt" src txt

[[file:sample_from_txt.xlsx][XLSX output]]

* Usage

MarkSheet is a command-line program.
In Windows you'll need to use the Command Prompt, on Mac the Terminal.
You will need a Java Runtime installed.
Change directory using =cd= to the folder where you placed Marksheet and you marking scheme.
Then type

#+BEGIN_SRC 
java -jar marksheet-2.0-SNAPSHOT.jar my_marking_scheme.txt marks.xlsx
#+END_SRC

to generate the spreadsheet, changing the file names as appropriate.
MarkSheet will run and print some messages to the terminal before exiting.

* Technical implementation

MarkSheet is written in Java and makes extensive use of the Apache POI libraries to manipulate Microsoft Excel documents.

* Known issues

** Non-normalisation

There is no normalisation of marks performed.
In other words, the question marks are added up with no scale factors.
In practice this means that you should not be using the "best of /n/" feature unless all questions have exactly the same number of marks.
The program does not automatically check that this is the case, however. 

** User interface

This is a command-line program.
A GUI is not currently under consideration, but may feature in future work.

* License

MarkSheet is Free Software, released under the GPL v3.

