#+TITLE: MarkSheet

By Peadar Grant

* Purpose

MarkSheet lets you generate Microsoft Excel (XLSX) files from an XML ot text description of the marking scheme (see sample.xml).
Whilst these files can be generated by hand, it was designed for use with exam-setting LaTeX classes that produce the appropriate text file alongside the generation of the PDF version of the exam papers and/or marking scheme.

* Download

** Binary

[[file:marksheet-2.0-SNAPSHOT.jar][Runnable JAR (dependencies included)]]

** Source

[[https://github.com/peadargrant/marksheet/][Sources on Github]]

* Marking scheme

Each question consists of a number of constituent parts. The program sets up the required formulae and allows taking the best of a number of equally-weighted questions.

** XML format

#+INCLUDE: "sample.xml" src xml

[[file:sample_from_xml.xlsx][XLSX output]]

** Text format

#+INCLUDE: "sample.txt" src txt

[[file:sample_from_txt.xlsx][XLSX output]]

Note: the text format for now does not allow a "best of" calculation to be done.

* Technical implementation

MarkSheet is written in Java and makes extensive use of the Apache POI libraries to manipulate Microsoft Excel documents.

* License

MarkSheet is Free Software, released under the GPL v3.

